blank_issues_enabled: false
contact_links:
    - name: 💻 Community Discord
      url: https://discord.gg/RUbZUZyByQ
      about: Contact Advance Systems 4042 for A-SYS support (update this link to your support channel).
